POST http://localhost:3000/api/addtasks
Content-Type: application/json

{
    "title": "Make Bunna"
}

###
GET http://localhost:3000/api/tasks

###
PUT http://localhost:3000/api/tasks/c745a2b9-bce7-4adc-ba64-0665b42852aa
// allows to change task title and also completion status
Content-Type: application/json

{
    "title": "make shiro",
    "completed": true
}

###
DELETE http://localhost:3000/api/tasks/c745a2b9-bce7-4adc-ba64-0665b42852aa